version: '2'

services:
  frontend:
    image: rypcarr/tf-demo-frontend
    environment:
      - BACKEND_HOST=backend
    ports:
      - "8080:80"
    depends_on:
      - backend
    links:
      - backend
    networks:
      tfdemo:
  backend:
    image: rypcarr/tf-demo-backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      tfdemo:
        aliases:
          - backend

  postgres:
    image: postgres:9
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
      - 5432
    networks:
      tfdemo:
        aliases:
          - postgres

networks:
  tfdemo:
    driver: bridge
